phase: local

url: http://localhost:10000

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 6a5ea0dfd6893cf7bbf9
            client-secret: 1761c0cf53ccf6bdf1061f6ea4e989f0293681d1