phase: local

url: http://localhost:10000

spring:
  pid:
    file: pid/jaeeunyoo-blog.pid
  security:
    oauth2:
      client:
        registration:
          github:
            redirect-uri: http://localhost:10000/login/oauth2/code/github
            client-id: 6a5ea0dfd6893cf7bbf9
            client-secret: 1761c0cf53ccf6bdf1061f6ea4e989f0293681d1
logging:
  file:
    name: /Users/nhn/workspace/jaeeunyoo/log/blog.log
  level:
    root: debug
  logback:
    rollingpolicy:
      max-history: 14